### ISSUE TITLE
URL creation still broken

### ISSUE THREAD

**Issue by 0x27** [HarryR/phuzz#1]
I have no idea why this bug is still cropping up... Backtrace below.

```
# python -m phuzz -o output/ -t tests/ -d
DEBUG:phuzz:Waiting for server...
PHP 5.6.4-4ubuntu6.4 Development Server started at Sun Sep 18 14:47:57 2016
Listening on http://127.0.0.1:25581
Document root is /scratch/skyhigh/wordpress-research/phuzz/tests
Press Ctrl-C to quit.
[Sun Sep 18 14:47:57 2016] 127.0.0.1:50010 Invalid request (Unexpected EOF)
INFO:phuzz:SyscallTracer started, pid: 14257
INFO:__main__:Scanning all files in tests/
DEBUG:phuzz:Retrieving 'http://127.0.0.1:25581afu1.php'
ERROR:__main__:FAIL...
Traceback (most recent call last):
  File "/scratch/skyhigh/wordpress-research/phuzz/phuzz/__main__.py", line 41, in main
    worker.run_file(os.path.join(path, filename))
  File "phuzz/__init__.py", line 415, in run_file
    return self.run_path(webpath)
  File "phuzz/__init__.py", line 420, in run_path
    return self.run(url)
  File "phuzz/__init__.py", line 428, in run
    trace = self.trace(url, state)
  File "phuzz/__init__.py", line 381, in trace
    resp = self._request_for_state(url, state)
  File "phuzz/__init__.py", line 374, in _request_for_state
    allow_redirects=False)
  File "/home/skyhighatrist/.local/lib/python2.7/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/home/skyhighatrist/.local/lib/python2.7/site-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/skyhighatrist/.local/lib/python2.7/site-packages/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/home/skyhighatrist/.local/lib/python2.7/site-packages/requests/models.py", line 347, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: 127.0.0.1:25581afu1.php
DEBUG:phuzz:SyscallTracer stopped, pid: 14257
```

**Comment by 0x27** [comment]
Screenshot, for posterity, of it now working against a large set of code from "the wild"

![itsalive](https://cloud.githubusercontent.com/assets/9094330/18616248/2a8c9b42-7db0-11e6-931b-e47fafd57b9f.png)
